config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'user/registrations'} # Custom controller for registrations
  resources :users, only: [:show]
  resources :friendships
  resources :user_stocks, except: [:show, :edit, :update]

  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

end

app/views/friends/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th colspan="3" class="page-header">
      <h2>My friends</h2>
    </th>
  </tr>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @friendships.each do |friend| %>
      <tr>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td>
          <%= link_to 'View Profile', user_path(friend), class: 'btn btn-primary btn-xs' %>
          <%= link_to 'Remove Friend', friendship_path(friend), method: :delete,
                            data: { confirm: 'Are you sure?'},
                            class: 'btn btn-xs btn-danger' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <h3>Search for Friends</h3>
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
      <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-10">
          <%= text_field_tag :search_param, params[:search_param], placeholder: 'First name, last name or email', autofocus: true,
                             class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
              <i class="fa fa-search"></i> Look up a friend
          <% end %>
        </div>
      </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @users %>
    <% if @users.size > 0 %>
      <div id="friend-lookup-results" class="well results-block col-md-10">
        <table class="search-results-table col-md-12">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <strong>Name: </strong>
                  <%= user.full_name %>
                </td>
                <td>
                  <strong>Email: </strong>
                  <%= user.email %></td>
                <td>
                  <strong>Profile: </strong>
                  <%= link_to 'View Profile', user_path(user), class: 'btn btn-xs btn-success' %>
                </td>
                <td>
                  <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to 'Add Friend',
                               add_friend_path(user: current_user, friend: user),
                               class: 'btn btn-xs btn-success',
                               method: :post %>
                  <% else %>
                    <span class="label label-primary">You are friends.</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class="lead col-md-12">
        No people match this criteria
      </p>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors">

  </div>
</div>